apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-frontend
        image: 023068192663.dkr.ecr.ap-south-1.amazonaws.com/demo-production:tagVersion
        ports:
        - containerPort: 3000
        imagePullSecrets:
          - name: demo
